name: deploy-site
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-site:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build:site

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}